<a href="https://colab.research.google.com/github/Sanket-2454/Excel-Sales-Analytics/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#numpy array function

import numpy as np
a = np.array([1,2,3]) #----> one d array is also called as vector
print(type(a))

<class 'numpy.ndarray'>


In [6]:
# 2-d array is also called as the matrix
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
# 3d array is also called as the tensor
c = np.array([[1,2,3],[4,5,6],[8,7,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [8 7 9]]


In [11]:
# here we do any datatype array like list, tuple,set,dict,str,bool,complex
d = np.array([1,2,3],dtype = complex)
print(d)


[1.+0.j 2.+0.j 3.+0.j]


In [12]:
# float numpy array
d = np.array([1,2,3],dtype = float)
print(d)

[1. 2. 3.]


In [17]:
# another way to create array
np.arange(1,11,2)# ----> (start,stop,end)


array([1, 3, 5, 7, 9])

In [18]:
# reshape function ---> convert given numpy array to another shape ----> reshape items product is always is between the arane
np.arange(1,11).reshape(2,5)
# matrices

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

ways to three intalize the array

In [23]:
# np.ones and np.zeros ---->

np.ones((3,4)) # row, column intalize the array with one value we pass values in the tuple format

np.zeros((5,4))  # row, column intalize the array with zeros value we pass values in the tuple format

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
# np.random
np.random.random((3,4))

array([[0.46369729, 0.7715942 , 0.19226151, 0.02371358],
       [0.66860705, 0.0278341 , 0.0758775 , 0.31566888],
       [0.55747484, 0.06441451, 0.89867058, 0.29025084]])

In [28]:
# np.linspace ----> linear space create equal distance point
np.linspace(-10,10,10,dtype=int) # ----> (start,end,and no of the element)


array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [27]:
#np.identity # digonal matrix is one other are 0
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [ ]:
# every numpy array has numpy class object
# so numpy can accese the attribute of the numpy class


In [48]:
a1 = np.arange(10,dtype = np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3= np.arange(8).reshape(2,2,2)
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [36]:
# ndim attributes show the dimiension of an given array is it , one d , two d

a1.ndim

a2.ndim

a3.ndim

3

In [39]:
# shape ----> give the shape of array mean how many rows and column ( row, column)
a1.shape

a2.shape

print(a3.shape) # (2, 2, 2) first two tell (2how many two d array in 3d ,(2*2)tell us the how many (row,column) in it)

(2, 2, 2)


In [43]:
# size ---> how many no of items

d = a2.size
print(a2)
print(d)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
12


In [50]:
# itemsize ----> tell us one type how many bytes it take in the meomry
a1.itemsize #  int it is two type int32 take 4byte, and int64 --is the default value for the int and the it take 8byte



4

In [56]:
# dtype ---> tell use the datatype of the items

a.dtype

print(a2.dtype)

a2.dtype

float64


dtype('float64')

Changing datatype

In [61]:
a3.astype(np.int32)

<class 'numpy.ndarray'>


In [64]:
# array operations ----> with array we can perform many mathmatical operation

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [66]:
# scaler opeator ---> operation withh single no

# arthmatic operation all works (*,/,-,+,%,//)
a1 //2 # here the a1 is matix and 2 is vector here we multiply the matrix and vector
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
# realtional operator all operation used (>,<,>=,<=,=,==)---> it return the boolean value if condtion true it return the true and if false it return false
print(a2>18)


[[False False False False]
 [False False False  True]
 [ True  True  True  True]]


In [70]:
# vector operation ---> used when we want to perform the opeartion on two numpy array shape should be same
# arthmatic operator(*,/,-,+)
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

Array function - there are so many function in numpy

In [82]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

print(a2)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [74]:
# min/max/sum/prod
np.min(a)

1

In [76]:
np.min(a2)

12

In [77]:
np.sum(a2)

210

In [78]:
np.prod(a)

1

In [79]:
# what if we need min from the row and column
#0--> column #1---> row
np.max(a1,axis = 1)# ----> (array,axis)

array([26., 88., 93.])

In [80]:
np.max(a1,axis=0)

array([93., 40., 88.])

In [81]:
# it is applicable for every function
np.sum(a2,axis=0)

array([48, 51, 54, 57])

In [85]:
# statsic operation (mean/median/std/var)
# also avilable for row and column by axis = 0
np.mean(a2)

# median
np.median(a)

# stdandard deviation
np.std(a2)

# variance
np.std(a)

0.0

In [88]:
# trignometric function ----> no use in data since

np.sin(10)

np.cos(12)

0.8438539587324921

In [91]:
# dot product ----> here 4 and 4 is the same it is condition of the dot product

a3 = np.arange(12).reshape(3,4)
a4 = np.arange(12,24).reshape(4,3)

np.dot(a3,a4)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [93]:
# log and expoents
np.log(a2)


array([[2.48490665, 2.56494936, 2.63905733, 2.7080502 ],
       [2.77258872, 2.83321334, 2.89037176, 2.94443898],
       [2.99573227, 3.04452244, 3.09104245, 3.13549422]])

In [94]:
# expoents
np.exp(a1)

array([[1.65163625e+38, 7.38905610e+00, 3.40427605e+29],
       [6.66317622e+40, 3.49342711e+19, 1.17191424e+16],
       [1.54553894e+25, 1.37338298e+32, 7.69478527e+23]])

In [100]:
#round/floor/ceil
np.round(np.random.random((2,3))*100)


np.ceil(6.3)


7.0

Indexing and slicing

In [103]:
b1 = np.arange(10)
b2 = np.arange(12).reshape(3,4)
b3 = np.arange(8).reshape(2,2,2)
b1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
b1[-1]

b1[6]

b3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [108]:
b2[1,2] #---> [rowno,columno] ---> start with zeros

6

In [110]:
b3[1,0,1] # -----> first accss 2d and same with above (2d,rowno,columnno)

5

In [ ]:
# adding the value in it modifiying

In [115]:
b3[0,1,1] = 9
b3

array([[[0, 1],
        [2, 9]],

       [[4, 5],
        [6, 7]]])

In [118]:
# slicing ----> give the range of the items also - stride + ve stride
b1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
b1[2:6:1]

array([2, 3, 4, 5])

In [123]:
b2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [126]:
# slicing in 2d
b2[0,:]

array([0, 1, 2, 3])

In [128]:
b2[:,2]

array([ 2,  6, 10])

In [132]:
b2[1,::3]

array([4, 7])

In [142]:
b2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [148]:
b4 = np.arange(27).reshape(3,3,3)
b4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [150]:
b4[1,:,1]

array([10, 13, 16])

In [152]:
b4[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [153]:
b4[1:,0,::2]

array([[ 9, 11],
       [18, 20]])

In [154]:
# iteration on the numpy array
a1

array([[88.,  2., 68.],
       [94., 45., 37.],
       [58., 74., 55.]])

In [155]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [156]:
for i in a2:
  print(i)

[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [157]:
for i in b4:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [158]:
for i in np.nditer(b4):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#Reshaping

In [ ]:
# In python result display temporary operation ----> and if result not display it is permant operation

In [159]:
# reshape
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [160]:
# Transpose ---> row convert to column and column convert to the row
# two type
np.transpose(a2)


array([[12, 16, 20],
       [13, 17, 21],
       [14, 18, 22],
       [15, 19, 23]])

In [161]:
#ravel ----> convert any dimension array to the single numpy array
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [164]:
# ravel
np.ravel(a2)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

stacking


In [167]:
# horizontal staking ---> adding two or more numpy array and shape should be same ---> used for the stack data together

s1 = np.arange(12).reshape(3,4)
s2 = np.arange(12,24).reshape(3,4)


z = np.hstack((s1,s2))
print(z)


[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [169]:
# vstack staking you applying slicing and indexing on it
p= np.vstack((s1,s2))
p[:,2]

array([ 2,  6, 10, 14, 18, 22])

Spliting

In [170]:
# v split --->
s2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [171]:
np.vsplit(s2,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [172]:
# h split
np.hsplit(s2,4)

[array([[12],
        [16],
        [20]]),
 array([[13],
        [17],
        [21]]),
 array([[14],
        [18],
        [22]]),
 array([[15],
        [19],
        [23]])]